---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: crm-os-starter
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: crm-os-starter@sha256:5b07562aa90aa8b166c279e59af4aebf42d8096784b51f172094b2f48b77e7f7
        namespace: myproject
      name: latest
