def name = "maven";
def mvnHome = tool name

node {

	stage('checkout & unit tests & build') {
	    git url: "https://github.com/dwi67/crm-reference.git"
	    sh "${mvnHome}/bin/mvn clean package"
	    junit allowEmptyResults: true, testResults: '**/target/surefire-reports/TEST-*.xml'
	}
}
