spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: DB_HOST_NAME
            value: postgresql
          - name: DB_PORT_NUMBER
            value: 5432
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: postgresql
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: postgresql
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: postgresql